sistema: "encoder_solo"

modelo:
  checkpoint: "PlanTL-GOB-ES/roberta-base-biomedical-clinical-es"
  adapter_path: "M1/saved_models/clinical_bert-distemist-lora"

chunking:
  window_words: 277
  overlap_words: 50

eval_set_path: "M2/examples/gold_examples.jsonl"

normalizacion:
  activa: false
  
output_path: "predictions/encoder_solo.json"
